language: node_js
node_js:
  - 0.10
services:
  - mongodb
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp mocha
  - gulp apidoc
after_script:
  - "npm run-script coverage"
  - "cat ./backend/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/871a92cb1cb3efe76a0a
    on_success: always
    on_failure: always
    on_start: always
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: LZrXEfoiNPEx9LmG0+fh3beJSbzzfhzDj+mcmgPdjcUFNO3tkAB2HDubbLJpI8ozCHT4LGPE+TgP/D+z16udV17fuaSDom5ZMaNyevGKG9zEjXvR/hL6eicqjmf5XMdFgB/nxUOidFI8loSV4neQQcPlQT+HZ4OprBfE5ijpTyFVQNmqKsf8IwgK4WML2wCb7ADIudmJ8kGC26vPQIteSTbzM2cUna3giORUcM0Hc8tUPYTIK9wdw2PZbzPQpDQFwrlUGqoaTbSedq9Pv1cJy6UdKCt2DZxeYHw0jaMHUdfqKp0wLt4Z7WDxMr5AucvFepNqJn8o4et1H+Hof4Ewj8qbMbIN9Up8jXGNS0cNhgVpwqhjeTPLYL5gxaBvB5mLCHCYeR4zC5vVdthtLAPV8ZxBoNKvDR4C5rfIWhzpxdT5DIOJ4NGKWY8Abnlh43HYeNlDHKLU4tToFOYdzTSNS41C8HBHfDPA9UbzFpROaMMqrCG7gg8nkC0mGqRcb3y9xvLyrSPPYyjtdwsM2qGPFV629qimb/GVj/TdaVMcmJq7ZRRBNXyPZdMDXZyuKFmc20Tat0xhPEDcusZGSzqj7TpS3yOnHNUtVLFtw2wdUgVfq6K5F3vG7AqKocQKXEgdhX5/jWcaIfkSA2UJnTOImXrisY+475WitLF1+A4CKes=
  app: gentle-coast-9691
  on:
    repo: CIVIS-project/YouPower
